### ISSUE TITLE
Todo until 10/04/2020

### ISSUE THREAD

**Issue by sztankatt** [Francis-Walker/DSAPlagueInc#2]
- [x] Reference Zone in each Node (#1)
- [x] Implement a radius function (both for Zone and Node) which for a given central point and radius returns the Nodes within that radius. This should be implemented once only for both and then called by the other object
- [x] How efficient is your radius function? Could you think of a better datastructure to decrease runtime?
- [x] Implement a possibility of having several Zones in a Universe. At each iteration each Node would have (initially) uniform probability of switching Zones
