### ISSUE TITLE
todo until 28/04/2020

### ISSUE THREAD

**Issue by sztankatt** [Francis-Walker/DSAPlagueInc#3]
@Francis-Walker 

- [x] Make every variable 'private' (with __x) and control whether it can be set/get with the functions

- [x] Cleanup and comment the code: each function at the beginning should have a short description, description of variables, and what it returns.

@Francis-Walker + Thabang

- [ ]  work out the complexities (space and time) of the functions and underlying algorithms. Then have a discussion about it, if you reach the same results thats good, if not than you need to figure out which of you is right

Thabang

- [ ] Run several simulations of the current code, with changing the parameters. Ideally you should have a code piece which will run these simulations automatically and in a structured way, and then will save the results for later analysis

- [ ] Write an analysis code piece, which should read the results of the prior simulations, and plot the population size, susceptible number, infected number, recovered number as a function of time. This will tell you which variable affects which result. 

- [ ] Play around with this, and think about what conclusions you can draw from these results
